apiVersion: v1
kind: Service
metadata:
  name: ml-api
  labels:
    app.kubernetes.io/name: ml-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ml-api
  ports:
    - name: http
      port: 80
      targetPort: http
