apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Example patches for prod can go here (e.g. higher resources, prod alias, enable HPA).
# resources:
#   - ../../base
#   - ../../base/hpa.yaml
